version: "3.6"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: node:18-alpine
    ports:
      - 4200:3000
  cms:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: craftcms/nginx:8.1
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8080:8080
  # console:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.php
  #   image: craftcms/cli:8.1
  #   volumes:
  #     - .:/app
  #   env_file: .env
  # command: ["php", "craft", "queue/listen"]
  mysql:
    image: mysql:oracle
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  db_data:
